// Public surface of the active exam engine.

export * from './constants.js'
export * from './contracts.js'
export * from './teacherExamSourceContext.js'
export * from './teacherBaseDataDiagnostics.js'
export * from './teacherBlockedDates.js'
export * from './teacherStructuredSource.js'
export * from './types.js'
export * from './adminReviewApplyWorkflow.js'
export * from './adminReviewApprovalEligibility.js'
export * from './adminReviewApprovalRequest.js'
export * from './adminReviewFinalReadiness.js'
export * from './adminReviewOfficializationPlan.js'
export * from './adminReviewOfficializationServerContract.js'
export * from './adminReviewSecondApprovalEligibility.js'
export * from './adminReviewSecondApproval.js'
export * from './adminReviewDecisions.js'
export * from './adminReviewPromotionWorkflow.js'
export * from './adminReviewWorkflow.js'

export * from './normalize/dates.js'
export * from './normalize/subjects.js'
export * from './normalize/teachers.js'
export * from './normalize/input.js'

export * from './rules/availability.js'
export * from './rules/calculateTeacherAssignmentLimit.js'
export * from './rules/halfPlusOne.js'
export * from './rules/roleConflicts.js'
export * from './rules/affinities.js'
export * from './rules/correlativities.js'
export * from './rules/regularCalls.js'
export * from './rules/timeRanges.js'

export * from './diagnostics/feasibility.js'
export * from './diagnostics/riskRanking.js'

export * from './planning/buildCandidates.js'
export * from './planning/buildVocalCandidates.js'
export * from './planning/assignTitular.js'
export * from './planning/assignVocales.js'
export * from './planning/compactMesas.js'
export * from './planning/repairTribunals.js'
export * from './planning/generateRegular.js'
export * from './planning/generateSpecial.js'
export * from './planning/draftSchedule/index.js'
export * from './planning/reviewedSchedule/index.js'
export * from './planning/tribunals/index.js'
export * from './planning/finalReview/index.js'

export * from './fieldTest/august2026FieldTestConfig.js'
export * from './fieldTest/runExamEngineV21FieldTest.js'
export * from './exports/exportDraftScheduleForTeachers.js'
export * from './exports/exportGeneratedTribunalsForReview.js'
export * from './exports/exportFinalTribunalsOfficial.js'
export * from './exports/exportFinalTribunalAlerts.js'

export * from './validation/validateMesa.js'
export * from './validation/validateCronograma.js'
export * from './validation/validateTeacherLoad.js'
export * from './validation/validateVocalAffinities.js'
export * from './validation/validateTribunals.js'
export * from './validation/reports.js'
export * from './validation/exportReport.js'
export * from './validation/validateReviewedDraftSchedule.js'
export * from './validation/validateGeneratedTribunals.js'
export * from './validation/validateFinalTribunals.js'

export * from './preview/index.js'

export * from './scoring/scoring.js'
