export const legacyWorkspaceSnapshotInstitutional = {
  alumnos: [],
  horariosDocentes: [
    {
      id: 'inst-horario-ing-1',
      profesor: 'Docente 1',
      docenteId: 'doc-inst-01',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'inst-horario-ing-2',
      profesor: 'Docente 2',
      docenteId: 'doc-inst-02',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      dia: 'martes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'inst-horario-ing-transversal',
      profesor: 'Docente 3',
      docenteId: 'doc-inst-03',
      carrera: 'Profesorado de Ingles',
      materia: 'INGT',
      nombreMateria: 'Ingles Transversal',
      dia: 'miercoles',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'inst-horario-discursivas',
      profesor: 'Docente 4',
      docenteId: 'doc-inst-04',
      carrera: 'Profesorado de Ingles',
      materia: 'PD3',
      nombreMateria: 'Practicas Discursivas III',
      dia: 'jueves',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'inst-horario-didactica-ingles',
      profesor: 'Docente 5',
      docenteId: 'doc-inst-05',
      carrera: 'Profesorado de Ingles',
      materia: 'DIDING4',
      nombreMateria: 'Didactica del Ingles IV',
      dia: 'viernes',
      turno: 'TARDE',
      inicio: '16:00',
      fin: '18:00',
    },
    {
      id: 'inst-horario-programacion',
      profesor: 'Docente 6',
      docenteId: 'doc-inst-06',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'inst-horario-tic',
      profesor: 'Docente 7',
      docenteId: 'doc-inst-07',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'TIC1',
      nombreMateria: 'Informatica y TIC',
      dia: 'martes',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'inst-horario-base-datos',
      profesor: 'Docente 8',
      docenteId: 'doc-inst-08',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'BD2',
      nombreMateria: 'Base de Datos II',
      dia: 'miercoles',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'inst-horario-practica-tecnica',
      profesor: 'Docente 9',
      docenteId: 'doc-inst-09',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRATEC2',
      nombreMateria: 'Practica Tecnica II',
      dia: 'jueves',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'inst-horario-arquitectura',
      profesor: 'Docente 6',
      docenteId: 'doc-inst-06',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'ARQ3',
      nombreMateria: 'Arquitectura de Software III',
      dia: 'viernes',
      turno: 'TARDE',
      inicio: '16:00',
      fin: '18:00',
    },
    {
      id: 'inst-horario-pedagogia',
      profesor: 'Docente 10',
      docenteId: 'doc-inst-10',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PED1',
      nombreMateria: 'Pedagogia General',
      dia: 'lunes',
      turno: 'TARDE',
      inicio: '15:00',
      fin: '17:00',
    },
    {
      id: 'inst-horario-practica-pedagogica',
      profesor: 'Docente 5',
      docenteId: 'doc-inst-05',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PRAPED3',
      nombreMateria: 'Practica Pedagogica III',
      dia: 'martes',
      turno: 'TARDE',
      inicio: '15:00',
      fin: '17:00',
    },
  ],
  docentes: [
    {
      id: 'doc-inst-01',
      nombre: 'Docente 1',
      especialidad: 'Lengua Inglesa',
    },
    {
      id: 'doc-inst-02',
      nombre: 'Docente 2',
      especialidad: 'Lengua Inglesa',
    },
    {
      id: 'doc-inst-03',
      nombre: 'Docente 3',
      especialidad: 'Ingles transversal',
    },
    {
      id: 'doc-inst-04',
      nombre: 'Docente 4',
      especialidad: 'Practicas Discursivas',
    },
    {
      id: 'doc-inst-05',
      nombre: 'Docente 5',
      especialidad: 'Didactica y practica pedagogica',
    },
    {
      id: 'doc-inst-06',
      nombre: 'Docente 6',
      especialidad: 'Programacion',
    },
    {
      id: 'doc-inst-07',
      nombre: 'Docente 7',
      especialidad: 'Informatica TIC',
    },
    {
      id: 'doc-inst-08',
      nombre: 'Docente 8',
      especialidad: 'Base de datos',
    },
    {
      id: 'doc-inst-09',
      nombre: 'Docente 9',
      especialidad: 'Practica tecnica',
    },
    {
      id: 'doc-inst-10',
      nombre: 'Docente 10',
      especialidad: 'Pedagogia',
    },
  ],
  planesEstudio: [
    {
      id: 'inst-plan-ing-1',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-ing-2',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-ing-transversal',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'INGT',
      nombreMateria: 'Ingles Transversal',
      anio: 3,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-discursivas-3',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'PD3',
      nombreMateria: 'Practicas Discursivas III',
      anio: 3,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-didactica-ingles-4',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'DIDING4',
      nombreMateria: 'Didactica del Ingles IV',
      anio: 4,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-programacion-1',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-tic-1',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'TIC1',
      nombreMateria: 'Informatica y TIC',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-base-datos-2',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'BD2',
      nombreMateria: 'Base de Datos II',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-practica-tecnica-2',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRATEC2',
      nombreMateria: 'Practica Tecnica II',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-arquitectura-3',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'ARQ3',
      nombreMateria: 'Arquitectura de Software III',
      anio: 3,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-pedagogia-1',
      carreraId: 'primaria',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PED1',
      nombreMateria: 'Pedagogia General',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'inst-plan-practica-pedagogica-3',
      carreraId: 'primaria',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PRAPED3',
      nombreMateria: 'Practica Pedagogica III',
      anio: 3,
      requiereMesa: true,
    },
  ],
  correlatividades: [
    {
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      correlativas: ['ING1'],
    },
    {
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'DIDING4',
      nombreMateria: 'Didactica del Ingles IV',
      correlativas: ['ING2', 'PD3'],
    },
    {
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'BD2',
      nombreMateria: 'Base de Datos II',
      correlativas: ['PRG1'],
    },
    {
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'ARQ3',
      nombreMateria: 'Arquitectura de Software III',
      correlativas: ['PRG1', 'TIC1'],
    },
    {
      carreraId: 'primaria',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PRAPED3',
      nombreMateria: 'Practica Pedagogica III',
      correlativas: ['PED1'],
    },
  ],
  fechaInicio: '2026-07-27',
  fechaFin: '2026-08-07',
  examType: 'regular',
  generationScope: {
    careers: [
      'Profesorado de Ingles',
      'Tecnicatura Superior en Desarrollo de Software',
      'Profesorado de Educacion Primaria',
    ],
    year: '',
    respectCorrelativities: true,
    applyHalfPlusOneRule: true,
    allowSameDayRelatedSubjects: true,
  },
  regularCallRanges: {
    first: {
      start: '2026-07-27',
      end: '2026-08-07',
    },
  },
  selectedSpecialSubjectKeys: [],
}
