export const legacyWorkspaceSnapshotStress = {
  alumnos: [
    {
      id: 'stress-alumno-ing-1',
      nombre: 'Alumno Ingles Stress',
      carrera: 'Profesorado de Ingles',
      anio: 3,
      materias: ['ING1', 'ING2', 'INGT', 'PD3'],
      estado: 'activo',
    },
    {
      id: 'stress-alumno-soft-1',
      nombre: 'Alumno Software Stress',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      anio: 2,
      materias: ['PRG1', 'TIC1'],
      estado: 'activo',
    },
    {
      id: 'stress-alumno-prim-1',
      nombre: 'Alumno Primaria Stress',
      carrera: 'Profesorado de Educacion Primaria',
      anio: 2,
      materias: ['DIDMAT1', 'PED1'],
      estado: 'activo',
    },
  ],
  horariosDocentes: [
    {
      id: 'stress-horario-ing-1',
      profesor: 'Ana Ingles I',
      docenteId: 'doc-stress-ing-1',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'stress-horario-ing-2',
      profesor: 'Bruno Ingles II',
      docenteId: 'doc-stress-ing-2',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'stress-horario-ing-transversal',
      profesor: 'Ana Ingles I',
      docenteId: 'doc-stress-ing-1',
      carrera: 'Profesorado de Ingles',
      materia: 'INGT',
      nombreMateria: 'Ingles Transversal',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '20:00',
      fin: '22:00',
    },
    {
      id: 'stress-horario-discursivas',
      profesor: 'Hector Discursivas',
      docenteId: 'doc-stress-disc-1',
      carrera: 'Profesorado de Ingles',
      materia: 'PD3',
      nombreMateria: 'Practicas Discursivas III',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'stress-horario-programacion',
      profesor: 'Carla Programacion',
      docenteId: 'doc-stress-soft-1',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'stress-horario-tic',
      profesor: 'Diego Informatica TIC',
      docenteId: 'doc-stress-soft-2',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'TIC1',
      nombreMateria: 'Informatica y TIC',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'stress-horario-alfabetizacion',
      profesor: 'Elena Primaria',
      docenteId: 'doc-stress-prim-1',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'ALF1',
      nombreMateria: 'Alfabetizacion Academica',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'stress-horario-titular-inexistente',
      docenteId: 'doc-stress-inexistente',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PED1',
      nombreMateria: 'Pedagogia General',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
  ],
  docentes: [
    {
      id: 'doc-stress-ing-1',
      nombre: 'Ana Ingles I',
      especialidad: 'Ingles',
      email: 'ana.stress@example.edu',
    },
    {
      id: 'doc-stress-ing-2',
      nombre: 'Bruno Ingles II',
      especialidad: 'Ingles',
      email: 'bruno.stress@example.edu',
    },
    {
      id: 'doc-stress-soft-1',
      nombre: 'Carla Programacion',
      especialidad: 'Programacion Informatica',
      email: 'carla.stress@example.edu',
    },
    {
      id: 'doc-stress-soft-2',
      nombre: 'Diego Informatica TIC',
      especialidad: 'Informatica TIC',
      email: 'diego.stress@example.edu',
    },
    {
      id: 'doc-stress-prim-1',
      nombre: 'Elena Primaria',
      especialidad: 'Educacion Primaria',
      email: 'elena.stress@example.edu',
    },
    {
      id: 'doc-stress-disc-1',
      nombre: 'Hector Discursivas',
      especialidad: 'Practicas Discursivas',
      email: 'hector.stress@example.edu',
    },
    {
      id: 'doc-stress-sin-disp',
      nombre: 'Natalia Sin Disponibilidad',
      especialidad: 'Ciencias de la Educacion',
      email: 'natalia.stress@example.edu',
    },
  ],
  planesEstudio: [
    {
      id: 'stress-plan-ing-1',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-ing-2',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-ing-transversal',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'INGT',
      nombreMateria: 'Ingles Transversal',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-pd3',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'PD3',
      nombreMateria: 'Practicas Discursivas III',
      anio: 3,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-prg-1',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-tic-1',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'TIC1',
      nombreMateria: 'Informatica y TIC',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'stress-plan-didmat-1',
      carreraId: 'primaria',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'DIDMAT1',
      nombreMateria: 'Didactica de la Matematica',
      anio: 2,
      requiereMesa: false,
    },
    {
      id: 'stress-plan-ped-1',
      carreraId: 'primaria',
      carrera: 'Profesorado de Educacion Primaria',
      materia: 'PED1',
      nombreMateria: 'Pedagogia General',
      anio: 1,
      requiereMesa: false,
    },
  ],
  correlatividades: [
    {
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      correlativas: ['ING1'],
    },
  ],
  fechaInicio: '2026-07-27',
  fechaFin: '2026-07-27',
  examType: 'regular',
  generationScope: {
    careers: [
      'Profesorado de Ingles',
      'Tecnicatura Superior en Desarrollo de Software',
      'Profesorado de Educacion Primaria',
    ],
    year: '',
    respectCorrelativities: true,
    applyHalfPlusOneRule: true,
    allowSameDayRelatedSubjects: true,
  },
  regularCallRanges: {
    first: {
      start: '2026-07-27',
      end: '2026-07-27',
    },
  },
  selectedSpecialSubjectKeys: [],
}
