export const legacyCronogramaResult = [
  {
    id: 'legacy-ing1-first',
    carrera: 'Profesorado de Ingles',
    materia: 'ING1',
    nombreMateria: 'Lengua Inglesa I',
    anio: 1,
    fechaIso: '2026-07-27',
    fecha: '27/07/2026',
    dia: 'Lunes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Ana Ingles I',
    vocal1: 'Carla Programacion',
    vocal2: 'Diego Base de Datos',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-ing2-first',
    carrera: 'Profesorado de Ingles',
    materia: 'ING2',
    nombreMateria: 'Lengua Inglesa II',
    anio: 2,
    fechaIso: '2026-07-28',
    fecha: '28/07/2026',
    dia: 'Martes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Bruno Ingles II',
    vocal1: 'Carla Programacion',
    vocal2: 'Diego Base de Datos',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-prg1-second',
    carrera: 'Tecnicatura Superior en Desarrollo de Software',
    materia: 'PRG1',
    nombreMateria: 'Programacion I',
    anio: 1,
    fechaIso: '2026-08-03',
    fecha: '03/08/2026',
    dia: 'Lunes',
    inicio: '19:00',
    fin: '21:00',
    profesorTitular: 'Carla Programacion',
    vocal1: 'Ana Ingles I',
    vocal2: 'Diego Base de Datos',
    exam_type: 'regular',
    exam_call: 'second',
    llamado: 'Segundo llamado',
    estado: 'pendiente',
  },
]

export const legacyCronogramaWithPendingTribunal = [
  ...legacyCronogramaResult,
  {
    id: 'legacy-bd1-first',
    carrera: 'Tecnicatura Superior en Desarrollo de Software',
    materia: 'BD1',
    nombreMateria: 'Base de Datos I',
    anio: 2,
    fechaIso: '',
    fecha: '',
    dia: '',
    inicio: '19:00',
    fin: '21:00',
    profesorTitular: 'Diego Base de Datos',
    vocal1: 'A designar',
    vocal2: 'A designar',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
    pendienteRevision: true,
  },
]

