export const legacyCronogramaInstitutionalResult = [
  {
    id: 'legacy-inst-ing1-first',
    carrera: 'Profesorado de Ingles',
    materia: 'inst-plan-ing-1',
    nombreMateria: 'Lengua Inglesa I',
    anio: 1,
    fechaIso: '2026-07-27',
    fecha: '27/07/2026',
    dia: 'Lunes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Docente 1',
    vocal1: 'Docente 6',
    vocal2: 'Docente 7',
    exam_type: 'regular',
    exam_call: 'primer llamado',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-inst-ing2-first',
    carrera: 'Profesorado de Ingles',
    materia: 'inst-plan-ing-2',
    nombreMateria: 'Lengua Inglesa II',
    anio: 2,
    fechaIso: '2026-07-28',
    fecha: '28/07/2026',
    dia: 'Martes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Docente 2',
    vocal1: 'Docente 6',
    vocal2: 'Docente 8',
    exam_type: 'regular',
    exam_call: 'PRIMER_LLAMADO',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-inst-ingt-first',
    carrera: 'Profesorado de Ingles',
    materia: 'inst-plan-ing-transversal',
    nombreMateria: 'Ingles Transversal',
    anio: 3,
    fechaIso: '2026-07-29',
    fecha: '29/07/2026',
    dia: 'Miercoles',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Docente 3',
    vocal1: 'Docente 1',
    vocal2: 'A designar',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente_revision',
    pendienteRevision: true,
  },
  {
    id: 'legacy-inst-pd3-first',
    carrera: 'Profesorado de Ingles',
    materia: 'inst-plan-discursivas-3',
    nombreMateria: 'Practicas Discursivas III',
    anio: 3,
    fechaIso: '2026-07-30',
    fecha: '30/07/2026',
    dia: 'Jueves',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Docente 4',
    vocal1: 'Docente 2',
    vocal2: 'Docente 5',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
    compactada: false,
    materiasAgrupadas: [],
  },
  {
    id: 'legacy-inst-tic1-first',
    carrera: 'Tecnicatura Superior en Desarrollo de Software',
    materia: 'inst-plan-tic-1',
    nombreMateria: 'Informatica y TIC',
    anio: 1,
    fechaIso: '2026-08-03',
    fecha: '03/08/2026',
    dia: 'Lunes',
    inicio: '19:00',
    fin: '21:00',
    profesorTitular: 'Docente 7',
    vocal1: 'Docente 6',
    vocal2: 'Docente 8',
    exam_type: 'regular',
    exam_call: '1',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-inst-practica-tecnica-first',
    carrera: 'Tecnicatura Superior en Desarrollo de Software',
    materia: 'inst-plan-practica-tecnica-2',
    nombreMateria: 'Practica Tecnica II',
    anio: 2,
    fechaIso: '2026-08-04',
    fecha: '04/08/2026',
    dia: 'Martes',
    inicio: '19:00',
    fin: '21:00',
    profesorTitular: 'Docente 9',
    vocal1: 'Docente 6',
    vocal2: '',
    exam_type: 'regular',
    exam_call: 'primer llamado',
    llamado: 'Primer llamado',
    estado: 'pendiente_revision',
    pendienteRevision: true,
  },
  {
    id: 'legacy-inst-practica-pedagogica-first',
    carrera: 'Profesorado de Educacion Primaria',
    materia: 'inst-plan-practica-pedagogica-3',
    nombreMateria: 'Practica Pedagogica III',
    anio: 3,
    fechaIso: '2026-08-05',
    fecha: '05/08/2026',
    dia: 'Miercoles',
    inicio: '15:00',
    fin: '17:00',
    profesorTitular: 'Docente 5',
    vocal1: 'Docente 5',
    vocal2: 'Docente 1',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
]
