export const legacyCronogramaStressResult = [
  {
    id: 'legacy-stress-ing1-first',
    carrera: 'Profesorado de Ingles',
    materia: 'stress-plan-ing-1',
    nombreMateria: 'Lengua Inglesa I',
    anio: 1,
    fechaIso: '2026-07-28',
    fecha: '28/07/2026',
    dia: 'Martes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Titular Legacy Ingles Diferente',
    vocal1: 'Carla Programacion',
    vocal2: 'Diego Informatica TIC',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
  {
    id: 'legacy-stress-ingt-first',
    carrera: 'Profesorado de Ingles',
    materia: 'stress-plan-ing-transversal',
    nombreMateria: 'Ingles Transversal',
    anio: 2,
    fechaIso: '2026-07-27',
    fecha: '27/07/2026',
    dia: 'Lunes',
    inicio: '20:00',
    fin: '22:00',
    profesorTitular: 'A designar',
    vocal1: 'A designar',
    vocal2: 'Bruno Ingles II',
    exam_type: 'regular',
    exam_call: 'primer llamado',
    llamado: 'Primer llamado',
    estado: 'pendiente_revision',
    pendienteRevision: true,
  },
  {
    id: 'legacy-stress-tic1-first',
    carrera: 'Tecnicatura Superior en Desarrollo de Software',
    materia: 'stress-plan-tic-1',
    nombreMateria: 'Informatica y TIC',
    anio: 2,
    fechaIso: '2026-07-29',
    fecha: '29/07/2026',
    dia: 'Miercoles',
    inicio: '19:00',
    fin: '21:00',
    profesorTitular: 'Diego Informatica TIC',
    vocal1: 'Carla Programacion',
    vocal2: 'A designar',
    exam_type: 'regular',
    exam_call: 'PRIMER_LLAMADO',
    llamado: 'Primer llamado',
    estado: 'pendiente_revision',
    pendienteRevision: true,
  },
  {
    id: 'legacy-stress-pd3-first',
    carrera: 'Profesorado de Ingles',
    materia: 'stress-plan-pd3',
    nombreMateria: 'Practicas Discursivas III',
    anio: 3,
    fechaIso: '2026-07-27',
    fecha: '27/07/2026',
    dia: 'Lunes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Hector Discursivas',
    vocal1: 'Ana Ingles I',
    vocal2: 'Bruno Ingles II',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
    compactada: false,
    materiasAgrupadas: [],
  },
  {
    id: 'legacy-stress-his1-extra',
    carrera: 'Profesorado de Historia',
    materia: 'HIS1',
    nombreMateria: 'Historia I',
    anio: 1,
    fechaIso: '2026-07-27',
    fecha: '27/07/2026',
    dia: 'Lunes',
    inicio: '18:00',
    fin: '20:00',
    profesorTitular: 'Titular Historia',
    vocal1: 'Ana Ingles I',
    vocal2: 'Elena Primaria',
    exam_type: 'regular',
    exam_call: 'first',
    llamado: 'Primer llamado',
    estado: 'pendiente',
  },
]
