export const legacyWorkspaceSnapshot = {
  alumnos: [
    {
      id: 'alumno-ing-1',
      nombre: 'Alumno Ingles Uno',
      carrera: 'Profesorado de Ingles',
      anio: 1,
      materias: ['ING1'],
      estado: 'activo',
    },
    {
      id: 'alumno-soft-1',
      nombre: 'Alumno Software Uno',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      anio: 1,
      materias: ['PRG1'],
      estado: 'activo',
    },
  ],
  horariosDocentes: [
    {
      id: 'horario-ing-1',
      profesor: 'Ana Ingles I',
      docenteId: 'doc-ing-1',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      dia: 'lunes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'horario-ing-2',
      profesor: 'Bruno Ingles II',
      docenteId: 'doc-ing-2',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      dia: 'martes',
      turno: 'NOCHE',
      inicio: '18:00',
      fin: '20:00',
    },
    {
      id: 'horario-soft-1',
      profesor: 'Carla Programacion',
      docenteId: 'doc-soft-1',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      dia: 'miercoles',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
    {
      id: 'horario-soft-2',
      profesor: 'Diego Base de Datos',
      docenteId: 'doc-soft-2',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'BD1',
      nombreMateria: 'Base de Datos I',
      dia: 'jueves',
      turno: 'NOCHE',
      inicio: '19:00',
      fin: '21:00',
    },
  ],
  docentes: [
    {
      id: 'doc-ing-1',
      nombre: 'Ana Ingles I',
      especialidad: 'Ingles',
      email: 'ana.ingles@example.edu',
    },
    {
      id: 'doc-ing-2',
      nombre: 'Bruno Ingles II',
      especialidad: 'Ingles',
      email: 'bruno.ingles@example.edu',
    },
    {
      id: 'doc-soft-1',
      nombre: 'Carla Programacion',
      especialidad: 'Programacion',
      email: 'carla.programacion@example.edu',
    },
    {
      id: 'doc-soft-2',
      nombre: 'Diego Base de Datos',
      especialidad: 'Base de datos',
      email: 'diego.basedatos@example.edu',
    },
  ],
  planesEstudio: [
    {
      id: 'plan-ing-1',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'plan-ing-2',
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      anio: 2,
      requiereMesa: true,
    },
    {
      id: 'plan-soft-1',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'PRG1',
      nombreMateria: 'Programacion I',
      anio: 1,
      requiereMesa: true,
    },
    {
      id: 'plan-soft-2',
      carreraId: 'soft',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      materia: 'BD1',
      nombreMateria: 'Base de Datos I',
      anio: 2,
      requiereMesa: true,
    },
  ],
  correlatividades: [
    {
      carreraId: 'prof-ingles',
      carrera: 'Profesorado de Ingles',
      materia: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      correlativas: ['ING1'],
    },
  ],
  fechaInicio: '2026-07-27',
  fechaFin: '2026-08-07',
  examType: 'regular',
  generationScope: {
    careers: ['Profesorado de Ingles', 'Tecnicatura Superior en Desarrollo de Software'],
    year: '',
    respectCorrelativities: true,
    applyHalfPlusOneRule: true,
    allowSameDayRelatedSubjects: true,
  },
  regularCallRanges: {
    first: {
      start: '2026-07-27',
      end: '2026-07-31',
    },
    second: {
      start: '2026-08-03',
      end: '2026-08-07',
    },
  },
  selectedSpecialSubjectKeys: [],
}

export const legacyWorkspaceSnapshotOneCall = {
  ...legacyWorkspaceSnapshot,
  fechaFin: '2026-07-31',
  regularCallRanges: {
    first: {
      start: '2026-07-27',
      end: '2026-07-31',
    },
  },
}

