export const newPreviewResult = {
  success: true,
  status: 'OK',
  plannedMesas: [
    {
      id: 'new-ing1-first',
      carrera: 'Profesorado de Ingles',
      carreraId: 'prof-ingles',
      materia: 'ING1',
      materiaId: 'ING1',
      nombreMateria: 'Lengua Inglesa I',
      anio: 1,
      fecha: '2026-07-27',
      displayDate: '2026-07-27',
      turno: 'NOCHE',
      estado: 'FECHA_TENTATIVA',
      titularId: 'doc-ing-1',
      titularNombre: 'Ana Ingles I',
      vocal1Id: 'doc-soft-1',
      vocal1Nombre: 'Carla Programacion',
      vocal2Id: 'doc-soft-2',
      vocal2Nombre: 'Diego Base de Datos',
      llamado: 'PRIMER_LLAMADO',
      compactada: false,
      materiasAgrupadas: [],
    },
    {
      id: 'new-ing2-first',
      carrera: 'Profesorado de Ingles',
      carreraId: 'prof-ingles',
      materia: 'ING2',
      materiaId: 'ING2',
      nombreMateria: 'Lengua Inglesa II',
      anio: 2,
      fecha: '2026-07-28',
      displayDate: '2026-07-28',
      turno: 'NOCHE',
      estado: 'FECHA_TENTATIVA',
      titularId: 'doc-ing-2',
      titularNombre: 'Bruno Ingles II',
      vocal1Id: 'doc-soft-2',
      vocal1Nombre: 'Diego Base de Datos',
      vocal2Id: 'doc-soft-1',
      vocal2Nombre: 'Carla Programacion',
      llamado: 'PRIMER_LLAMADO',
      compactada: false,
      materiasAgrupadas: [],
    },
    {
      id: 'new-prg1-second',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      carreraId: 'soft',
      materia: 'PRG1',
      materiaId: 'PRG1',
      nombreMateria: 'Programacion I',
      anio: 1,
      fecha: '2026-08-03',
      displayDate: '2026-08-03',
      turno: 'NOCHE',
      estado: 'FECHA_TENTATIVA',
      titularId: 'doc-soft-1',
      titularNombre: 'Carla Programacion',
      vocal1Id: 'doc-ing-1',
      vocal1Nombre: 'Ana Ingles I',
      vocal2Id: 'doc-soft-2',
      vocal2Nombre: 'Diego Base de Datos',
      llamado: 'SEGUNDO_LLAMADO',
      compactada: false,
      materiasAgrupadas: [],
    },
  ],
  unassignedMesas: [],
  errors: [],
  warnings: [],
  metadata: {
    compactMode: 'safe',
    compactacionEjecutada: true,
    compactaciones: [],
  },
}

export const newPreviewWithCompaction = {
  ...newPreviewResult,
  plannedMesas: [
    {
      ...newPreviewResult.plannedMesas[0],
      id: 'new-ing-compactada-first',
      materia: 'ING1 / ING2',
      materiaId: 'ING1',
      nombreMateria: 'Lengua Inglesa I / Lengua Inglesa II',
      compactada: true,
      materiasAgrupadas: [
        {
          materia: 'ING1',
          materiaId: 'ING1',
          nombreMateria: 'Lengua Inglesa I',
          carrera: 'Profesorado de Ingles',
        },
        {
          materia: 'ING2',
          materiaId: 'ING2',
          nombreMateria: 'Lengua Inglesa II',
          carrera: 'Profesorado de Ingles',
        },
      ],
    },
    newPreviewResult.plannedMesas[2],
  ],
  metadata: {
    ...newPreviewResult.metadata,
    compactaciones: [
      {
        id: 'compact-ing-1',
        success: true,
        materias: ['ING1', 'ING2'],
      },
    ],
  },
}

export const newPreviewWithUnassigned = {
  ...newPreviewResult,
  unassignedMesas: [
    {
      id: 'new-bd1-unassigned',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      carreraId: 'soft',
      materia: 'BD1',
      materiaId: 'BD1',
      nombreMateria: 'Base de Datos I',
      anio: 2,
      llamado: 'PRIMER_LLAMADO',
      estado: 'SIN_FECHA',
      reason: 'SIN_FECHA_VALIDA',
      message: 'No hay fecha valida para la mesa.',
      errorsCount: 1,
      warningsCount: 0,
      reviewRequired: true,
    },
  ],
  errors: [
    {
      code: 'SIN_FECHA_VALIDA',
      severity: 'critical',
      message: 'No hay fecha valida para la mesa.',
      materia: 'BD1',
      carrera: 'Tecnicatura Superior en Desarrollo de Software',
      llamado: 'PRIMER_LLAMADO',
    },
  ],
}

