export const DOCENTE_MATERIA_TEMPLATE_COLUMNS = [
  'carrera',
  'materia_codigo',
  'materia_nombre',
  'anio',
  'docente',
  'dni_docente',
  'rol_en_materia',
  'estado_asignacion',
  'vigencia_desde',
  'vigencia_hasta',
  'docente_reemplazado',
  'requiere_mesa',
  'observaciones',
]

export function buildDocenteMateriaTemplateRows() {
  return [
    {
      carrera: 'Profesorado de Ingles',
      materia_codigo: 'ING-001',
      materia_nombre: 'Ingles I',
      anio: '1',
      docente: 'Docente Titular Activo',
      dni_docente: '',
      rol_en_materia: 'TITULAR',
      estado_asignacion: 'ACTIVO',
      vigencia_desde: '2026-01-01',
      vigencia_hasta: '',
      docente_reemplazado: '',
      requiere_mesa: 'SI',
      observaciones: 'Ejemplo: titular vigente.',
    },
    {
      carrera: 'Profesorado de Ingles',
      materia_codigo: 'DID-002',
      materia_nombre: 'Didactica del Ingles I',
      anio: '2',
      docente: 'Docente Titular en Licencia',
      dni_docente: '',
      rol_en_materia: 'TITULAR',
      estado_asignacion: 'LICENCIA',
      vigencia_desde: '2026-01-01',
      vigencia_hasta: '',
      docente_reemplazado: '',
      requiere_mesa: 'SI',
      observaciones: 'Ejemplo: titular no activo temporalmente.',
    },
    {
      carrera: 'Profesorado de Ingles',
      materia_codigo: 'DID-002',
      materia_nombre: 'Didactica del Ingles I',
      anio: '2',
      docente: 'Docente Reemplazo Activo',
      dni_docente: '',
      rol_en_materia: 'REEMPLAZO',
      estado_asignacion: 'ACTIVO',
      vigencia_desde: '2026-06-01',
      vigencia_hasta: '',
      docente_reemplazado: 'Docente Titular en Licencia',
      requiere_mesa: 'SI',
      observaciones: 'Ejemplo: reemplazo vigente del titular en licencia.',
    },
    {
      carrera: 'Tecnicatura Superior en Turismo',
      materia_codigo: 'TUR-099',
      materia_nombre: 'Taller Institucional sin Mesa',
      anio: '1',
      docente: 'Docente Taller',
      dni_docente: '',
      rol_en_materia: 'TITULAR',
      estado_asignacion: 'ACTIVO',
      vigencia_desde: '',
      vigencia_hasta: '',
      docente_reemplazado: '',
      requiere_mesa: 'NO',
      observaciones: 'Ejemplo: materia no requerida para mesa.',
    },
    {
      carrera: 'Profesorado de Ingles',
      materia_codigo: 'PRA-003',
      materia_nombre: 'Practica Profesional Docente III',
      anio: '3',
      docente: 'Docente Titular Practica',
      dni_docente: '',
      rol_en_materia: 'TITULAR',
      estado_asignacion: 'ACTIVO',
      vigencia_desde: '2026-01-01',
      vigencia_hasta: '',
      docente_reemplazado: '',
      requiere_mesa: 'SI',
      observaciones: 'Ejemplo: practica profesional con titular explicitado.',
    },
    {
      carrera: 'Profesorado de Ingles',
      materia_codigo: 'PRA-003',
      materia_nombre: 'Practica Profesional Docente III',
      anio: '3',
      docente: 'Docente Co Docente Practica',
      dni_docente: '',
      rol_en_materia: 'CO_DOCENTE',
      estado_asignacion: 'ACTIVO',
      vigencia_desde: '2026-01-01',
      vigencia_hasta: '',
      docente_reemplazado: '',
      requiere_mesa: 'SI',
      observaciones: 'Ejemplo: practica profesional multidocente permitida.',
    },
  ]
}
